export const purple = '#292477'
export const gray = '#757575'
export const white = '#fff'
export const red = '#b71845'
export const orange = '#f26f28'
export const blue = '#4e4cb8'
export const lightPurp = '#7c53c3'
export const pink = '#b93fb3'
export const green = '#0b6623'

export const coolblue = '#eff'
export const lightgray = '#eee'
// export const  = '#eee'
// export const lightgray = '#eee'
// export const lightgray = '#eee'

